### ISSUE TITLE
ROS control not working in baseControl

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/navigation#11]
Hi,
We've again been running into issues with this repo. We cannot get the iKart to move using ROS velocity commands. We have checked and we receive the velocity commands sent by ROS (https://github.com/robotology/navigation/blob/master/src/baseControl/input.cpp#L591). However the iKart does not move.

There are a lot of magic numbers in `baseControl` and documentation is close to non existing, so it is really hard to figure out why it does not work.

However, I got the problem tracked down to following:
In https://github.com/robotology/navigation/blob/master/src/baseControl/input.cpp#L591-L595, a `Bottle b` is created, and 4(!) values are put in (a magical "3", the linear velocities in `x` and `y` and the angular velocity). Then, `read_speed_cart()` is called. This sets `pwm_gain = b->get(4).asDouble();`, however remember that there are only 4 values in `b`, so `b->get(4).isNull() == true`. However, `asDouble` (for whatever reason not really logical to me) returns 0. Thus, the PWM gain is always 0, and the robot moves. What should the default PWM gain be?

Would be great if you get back to me @randaz81.

Thanks, Tobias

**Comment by randaz81** [comment]
fixed by 7c09766269e. Thank you.

**Comment by Tobias-Fischer** [comment]
Thanks!
